Models/Session.cs
using System;
using System.Collections.Generic;

namespace MvcMobile.Models
{
    public class Session
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public IEnumerable<string> Speakers { get; set; }
        public IEnumerable<string> Tags { get; set; }
        public string Room { get; set; }
        public string Code { get; set; }
        public DateTime StartDate { get; set; }
        public string DateText { get; set; }
    }
}

Models/Sessions.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Xml.Linq;

namespace MvcMobile.Models
{
    // Could be loaded from a DB, but an in-memory collection is fine for this example
    public static class Sessions
    {
        public static IList<Session> All { get; private set; }

        static Sessions()
        {
            // Parse the XML
            var xmlFilename = HttpContext.Current.Server.MapPath("~/App_Data/Sessions/RawSessionsData.xml");
            var xml = XDocument.Load(xmlFilename);
            var sessions = from s in xml.Root.Elements("Session")
                           select new Session {
                               Title = s.Element("Title").Value,
                               Description = s.Element("Description").Value,
                               Room = s.Element("Room").Value,
                               Code = s.Element("Code").Value,
                               DateText = s.Element("Date").Value,
                               StartDate = ParseStartDate(s.Element("Date").Value),
                               Speakers = s.Elements("Speaker").Select(x => x.Value),
                               Tags = s.Elements("Tag").Select(x => x.Value)
                           };
            All = sessions.ToList();
        }

        private static DateTime ParseStartDate(string dateString)
        {
            // Parse text strictly of the form "Thu, Apr 14 12:00 PM - 1:00 PM"
            var date = dateString.Substring(5, 6);
            var time = dateString.Substring(11, 9);
            var combined = date + " 2011, " + time;
            return DateTime.Parse(combined);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using MvcMobile.Models;

namespace MvcMobile.Controllers {
    public class HomeController : Controller {
        public ViewResult Index() {
            ViewBag.NumSessions = Sessions.All.Count;
            return View();
        }

        public ViewResult AllSpeakers() {
            var allSpeakers = Sessions.All.SelectMany(x => x.Speakers).Distinct().OrderBy(x => x);
            return View(allSpeakers);
        }

        public ViewResult AllTags() {
            var allTags = Sessions.All.SelectMany(x => x.Tags).Distinct().OrderBy(x => x);
            return View(allTags);
        }

        public ViewResult AllDates() {
            var allDates = Sessions.All.Select(x => x.StartDate).Distinct().OrderBy(x => x);
            return View(allDates);
        }

        public ViewResult SessionsBySpeaker(string speaker) {
            ViewBag.Title = "Sessions by " + speaker;
            var sessions = Sessions.All.Where(session => session.Speakers.Contains(speaker)).OrderBy(x => x.StartDate);
            return View("SessionsTable", sessions);
        }

        public ViewResult SessionsByTag(string tag) {
            ViewBag.Title = "Sessions tagged " + tag;
            var sessions = Sessions.All.Where(session => session.Tags.Contains(tag)).OrderBy(x => x.Title);
            return View("SessionsTable", sessions);
        }

        public ViewResult SessionsByDate(DateTime date) {
            ViewBag.Title = "Sessions on at " + date.ToString("ddd, MMM dd, h:mm tt");
            var sessions = Sessions.All.Where(session => session.StartDate == date).OrderBy(x => x.Title);
            return View("SessionsTable", sessions);
        }

        public ActionResult SessionByCode(string code) {
            if (String.IsNullOrEmpty(code)) {
                return RedirectToAction("AllTags");
            }

            var session = Sessions.All.Single(x => x.Code == code);
            return View(session);
        }
    }
}

Controllers/ViewSwitcherController.cs
using System.Web.Mvc;
using System.Web.WebPages;

namespace MvcMobile.Controllers
{
    public class ViewSwitcherController : Controller
    {
        public RedirectResult SwitchView(bool mobile, string returnUrl) {
            if (Request.Browser.IsMobileDevice == mobile)
                HttpContext.ClearOverriddenBrowser();
            else
                HttpContext.SetOverriddenBrowser(mobile ? BrowserOverride.Mobile : BrowserOverride.Desktop);

            return Redirect(returnUrl);
        }
    }
}

Views/Home/AllDates.Mobile.cshtml
@model IEnumerable<DateTime>
@{
    ViewBag.Title = "All dates";
    DateTime lastDay = default(DateTime);
}

<ul data-role="listview">
    @foreach(var date in Model) {
        if (date.Date != lastDay) {
            lastDay = date.Date;
            <li data-role="list-divider">@date.Date.ToString("ddd, MMM dd")</li>
        }
        <li>@Html.ActionLink(date.ToString("h:mm tt"), "SessionsByDate", new { date })</li>
    }
</ul>

Views/Home/AllDates.cshtml
@model IEnumerable<DateTime>

@{
    ViewBag.Title = "All dates";
}

<h2>Dates</h2>

<ul>
    @foreach(var date in Model) {
        <li>@Html.ActionLink(date.ToString("ddd, MMM dd, h:mm tt"), "SessionsByDate", new { date })</li>
    }
</ul>

Views/Home/AllSpeakers.Mobile.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "All speakers";
}


<ul data-role="listview" data-filter="true">
    @foreach (var speaker in Model) {
        <li>@Html.ActionLink(speaker, "SessionsBySpeaker", new { speaker })</li>
    }
</ul>

Views/Home/AllSpeakers.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "All speakers";
  //  DisplayModes.RequireConsistentDisplayMode = false;
}

<h2>Speakers</h2>

<ul>
    @foreach (var speaker in Model) {
        <li>@Html.ActionLink(speaker, "SessionsBySpeaker", new { speaker })</li>
    }
</ul>

Views/Home/AllTags.Mobile.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "All tags";
}


<ul data-role="listview" data-filter="true">
    @foreach(var tag in Model) {
        <li>@Html.ActionLink(tag, "SessionsByTag", new { tag })</li>
    }
</ul>

Views/Home/AllTags.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "All tags";
}

<h2>Tags</h2>

<ul>
    @foreach(var tag in Model) {
        <li>@Html.ActionLink(tag, "SessionsByTag", new { tag })</li>
    }
</ul>

Views/Home/AllTags.iPhone.cshtml
@model IEnumerable<string>

@{
    ViewBag.Title = "All tags iPhone";
}


<ul data-role="listview" data-filter="true">
    @foreach(var tag in Model) {
        <li>@Html.ActionLink(tag, "SessionsByTag", new { tag })</li>
    }
</ul>

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<h2>MIX 2011 - browse @ViewBag.NumSessions sessions</h2>
<p>
    Conference Session Browsing Sample. Click a menu item for more information. 
</p>

Views/Home/SessionByCode.Mobile.cshtml
@model MvcMobile.Models.Session

@{
    ViewBag.Title = "Session details";
}

<h2>@Model.Title</h2>
<p>
    <strong>@Model.DateText</strong> in <strong>@Model.Room</strong>
</p>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Speakers</li>
    @foreach (var speaker in Model.Speakers) {
        <li>@Html.ActionLink(speaker, "SessionsBySpeaker", new { speaker })</li>
    }
</ul>

<p>@Model.Description</p>
<h4>Code: @Model.Code</h4>

<ul data-role="listview" data-inset="true">
    <li data-role="list-divider">Tags</li>
    @foreach (var tag in Model.Tags) {
        <li>@Html.ActionLink(tag, "SessionsByTag", new { tag })</li>
    }
</ul>

Views/Home/SessionByCode.cshtml
@model MvcMobile.Models.Session

@{
    ViewBag.Title = "Session";
}

<div class="session">
    <h1>@Html.ActionLink(Model.Title, "SessionByCode", new { Model.Code })</h1>
    <h2>
        @{
            var index = 0;
            foreach (var speaker in Model.Speakers) {
                if (index > 0) {
                    if (index == Model.Speakers.Count() - 1) { <text> and </text> } else {<text>, </text> }
                }
                @Html.ActionLink(speaker, "SessionsBySpeaker", new { speaker })
                index++;
            }
        }
    </h2>
    <h3>When: @Model.DateText</h3>
    <h3>Where: @Model.Room</h3>
    <h3>Code: @Model.Code</h3>
    <p>@Model.Description</p>
    <p>
        Tags:
        @foreach (var tag in Model.Tags) {
            @Html.ActionLink(tag, "SessionsByTag", new { tag })
            <text> </text>
        }
    </p>
</div>

Views/Home/SessionsTable.Mobile.cshtml
@using MvcMobile.Models
@model IEnumerable<Session>

<ul data-role="listview">
    @foreach(var session in Model) {
        <li>
            <a href="@Url.Action("SessionByCode", new { session.Code })">
                <h3>@session.Title</h3>
                <p><strong>@string.Join(", ", session.Speakers)</strong></p>
                <p>@session.DateText</p>
            </a>
        </li>                                           
    }    
</ul>

Views/Home/SessionsTable.cshtml
@using MvcMobile.Models
@model IEnumerable<Session>

<h2>@ViewBag.Title</h2>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Speaker(s)</th>
            <th>Date</th>
            <th>Room</th>
            <th>Tags</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var session in Model) {
            <tr>
                <td>@Html.ActionLink(session.Title, "SessionByCode", new { session.Code })</td>
                <td>@Html.Partial("_SpeakersLinks", session)</td>
                <td>@session.DateText</td>
                <td>@session.Room</td>
                <td>@Html.Partial("_TagsLinks", session)</td>
            </tr>                                           
        }
    </tbody>
</table>

Views/Home/_SpeakersLinks.cshtml
@using MvcMobile.Models
@model Session

@{
    var index = 0;
    foreach (var speaker in Model.Speakers.OrderBy(x => x)) {
        if (index > 0) {
            if (index == Model.Speakers.Count() - 1) { <text> and </text> } else {<text>, </text> }
        }
        @Html.ActionLink(speaker, "SessionsBySpeaker", new { speaker })
        index++;
    }
}

Views/Home/_TagsLinks.cshtml
@using MvcMobile.Models
@model Session

@foreach (var tag in Model.Tags.OrderBy(x => x)) {
    @Html.ActionLink(tag, "SessionsByTag", new { tag })
    <text> </text>
}

Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0b3.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.3.min.js")"></script>
    <script type="text/javascript">
        $(document).bind("mobileinit", function () {
            // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
            // when navigating from a mobile to a non-mobile page), hence disabling it.
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.0b3.min.js")"></script>
</head>
<body>
    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher")
        <div data-role="header" align="center">
            @Html.ActionLink("Home", "Index", "Home")
            @Html.ActionLink("Date", "AllDates")
            @Html.ActionLink("Speaker", "AllSpeakers")
            @Html.ActionLink("Tag", "AllTags")
        </div>
        <div data-role="header">
        <h1>  @ViewBag.Title</h1>
        
        </div>
        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.6.3.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/AjaxLogin.js")" type="text/javascript"></script>
        <meta name="viewport" content="width=device-width">

</head>
<body>
    <div class="page">
            @Html.Partial("_ViewSwitcher")
        <div id="header">

            <div id="logindisplay"></div>
            <div id="title">
                <h1> MVC4 Conference </h1>
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Browse by date", "AllDates", "Home")</li>
                    <li>@Html.ActionLink("Browse by speaker", "AllSpeakers", "Home")</li>
                    <li>@Html.ActionLink("Browse by tag", "AllTags", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

Views/Shared/_Layout.iPhone.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="@Url.Content("~/Content/jquery.mobile-1.0b3.min.css")" />
    <link rel="stylesheet" href="@Url.Content("~/Content/Site.Mobile.css")" />
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery-1.6.3.min.js")"></script>
    <script type="text/javascript">
        $(document).bind("mobileinit", function () {
            // As of Beta 2, jQuery Mobile's Ajax navigation does not work in all cases (e.g.,
            // when navigating from a mobile to a non-mobile page), hence disabling it.
            $.mobile.ajaxEnabled = false;
        });
    </script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.mobile-1.0b3.min.js")"></script>
</head>
<body>
    <div data-role="page" data-theme="a">
        @Html.Partial("_ViewSwitcher") (iPhone)
        <div data-role="header" align="center">
            @Html.ActionLink("Home", "Index", "Home")
            @Html.ActionLink("Date", "AllDates")
            @Html.ActionLink("Speaker", "AllSpeakers")
            @Html.ActionLink("Tag", "AllTags")
        </div>
        <div data-role="header">
        <h1>  @ViewBag.Title</h1>
        
        </div>
        <div data-role="content">
            @RenderSection("featured", false)
            @RenderBody()
        </div>
    </div>
</body>
</html>

Views/Shared/_ViewSwitcher.cshtml
@if (Request.Browser.IsMobileDevice && Request.HttpMethod == "GET")
{
    <div class="view-switcher ui-bar-a">
        @if (ViewContext.HttpContext.GetOverriddenBrowser().IsMobileDevice)
        {
            @: Displaying mobile view
            @Html.ActionLink("Desktop view", "SwitchView", "ViewSwitcher", new { mobile = false, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        } 
        else 
        {
            @: Displaying desktop view
            @Html.ActionLink("Mobile view", "SwitchView", "ViewSwitcher", new { mobile = true, returnUrl = Request.Url.PathAndQuery }, new { rel = "external" })
        }
    </div>
}

Views/Shared/z_Layout.iPhone.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.6.3.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.11.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/AjaxLogin.js")" type="text/javascript"></script>
        <meta name="viewport" content="width=device-width">

</head>
<body>
    <div class="page">
        <div id="header">
            <div id="logindisplay"></div>
            <div id="title">
                <h1> Conference (iPhone)</h1>
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Date", "AllDates", "Home")</li>
                    <li>@Html.ActionLink("Speaker", "AllSpeakers", "Home")</li>
                    <li>@Html.ActionLink("Tag", "AllTags", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>